---
- name: Install the geoipupdate deb package from GitHub
  when: ansible_os_family == "Debian"
  block:
    - name: Download the geoipupdate Debian package
      ansible.builtin.get_url:
        dest: /tmp/geoipupdate.deb
        mode: u=rw,g=r,o=r
        url: "{{ geoipupdate_package_url }}"

    - name: Install geoipupdate Debian package
      ansible.builtin.apt:
        deb: /tmp/geoipupdate.deb

- name: Install the geoipupdate rpm package from GitHub
  when: ansible_os_family == "RedHat"
  block:
    - name: Install geoipupdate via dnf
      ansible.builtin.dnf:
        # The geoipupdate RPM is currently unsigned:
        # https://github.com/maxmind/geoipupdate/issues/180
        disable_gpg_check: true
        name: "{{ geoipupdate_package_url }}"
