---
- name: Install the geoipupdate deb package from GitHub
  when: ansible_os_family == "Debian"
  block:
    - name: Download the geoipupdate Debian package
      ansible.builtin.get_url:
        dest: /tmp/geoipupdate.deb
        mode: u=rw,g=r,o=r
        url: "{{ geoipupdate_package_url }}"

    - name: Install geoipupdate Debian package
      ansible.builtin.apt:
        deb: /tmp/geoipupdate.deb

- name: Install the geoipupdate rpm package from GitHub
  when: ansible_os_family == "RedHat"
  block:
    - name: Install geoipupdate via dnf
      ansible.builtin.dnf:
        # The geoipupdate RPM is currently unsigned:
        # https://github.com/maxmind/geoipupdate/issues/180
        disable_gpg_check: true
        name: "{{ geoipupdate_package_url }}"

- name: Set up automatic updates for GeoIP databases
  when: geoip2_geoipupdate_auto_update
  block:
    - name: Write the geoipupdate systemd service file
      ansible.builtin.template:
        dest: /etc/systemd/system/{{ geoip2_geoipupdate_service_name }}.service
        mode: u=rw,g=r,o=r
        src: geoipupdate.service.j2

    - name: Write the geoipupdate systemd timer file
      ansible.builtin.template:
        dest: /etc/systemd/system/{{ geoip2_geoipupdate_service_name }}.timer
        mode: u=rw,g=r,o=r
        src: geoipupdate.timer.j2

    - name: Start and enable the geoipupdate systemd timer
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        name: "{{ geoip2_geoipupdate_service_name }}.timer"
        state: started
