---
- name: Verify that MaxMind information is provided
  ansible.builtin.fail:
    msg: This role requires a MaxMind account ID and license key.
  when:
    # yamllint complains about the length of this line, but there is
    # no clean way to break it up.
    # yamllint disable-line rule:line-length
    - geoip2_maxmind_account_id is not defined or geoip2_maxmind_license_key is not defined

# Install some necessary prerequisites
- name: Install prerequisites
  ansible.builtin.package:
    name:
      - gzip
      - tar

- name: Ensure the directory in which to store the database file exists
  ansible.builtin.file:
    mode: u=rwx,g=rx,o=rx
    path: "{{ geoip2_database_directory }}"
    state: directory

- name: Install the specified MaxMind database edition
  ansible.builtin.include_tasks: install_database_edition.yml
  loop: "{{ geoip2_maxmind_editions }}"
  loop_control:
    loop_var: database_edition

- name: Install the geoipupdate tool
  when: geoip2_install_geoipupdate
  block:
    - name: Load var file with package URL based on the OS type
      ansible.builtin.include_vars: >-
        {{
          lookup(
            "ansible.builtin.first_found",
            params
          )
        }}
      vars:
        params:
          files:
            - >-
              geoipupdate_{{ ansible_distribution }}_{{
              ansible_distribution_release }}.yml
            - geoipupdate_{{ ansible_distribution }}.yml
            - geoipupdate_{{ ansible_os_family }}.yml
          paths:
            - "{{ role_path }}/vars"

    - name: Load tasks file with install tasks based on the OS type
      ansible.builtin.include_tasks: >-
        {{
          lookup(
            "ansible.builtin.first_found",
            params
          )
        }}
      vars:
        params:
          files:
            - >-
              install_geoipupdate_{{ ansible_distribution
              }}_{{ ansible_distribution_release }}.yml
            - install_geoipupdate_{{ ansible_distribution }}.yml
            - install_geoipupdate_{{ ansible_os_family }}.yml
          paths:
            - "{{ role_path }}/tasks"

    - name: Write the geoipupdate configuration file
      ansible.builtin.template:
        dest: /etc/GeoIP.conf
        mode: u=rw,g=r,o=r
        src: GeoIP.conf.j2

    - name: Set up automatic updates for GeoIP databases
      when: geoip2_geoipupdate_auto_update
      block:
        - name: Write the geoipupdate systemd service file
          ansible.builtin.template:
            dest: /etc/systemd/system/{{ geoip2_geoipupdate_service_name }}.service
            mode: u=rw,g=r,o=r
            src: geoipupdate.service.j2

        - name: Write the geoipupdate systemd timer file
          ansible.builtin.template:
            dest: /etc/systemd/system/{{ geoip2_geoipupdate_service_name }}.timer
            mode: u=rw,g=r,o=r
            src: geoipupdate.timer.j2

        - name: Start and enable the geoipupdate systemd timer
          ansible.builtin.systemd:
            daemon_reload: true
            enabled: true
            name: "{{ geoip2_geoipupdate_service_name }}.timer"
            state: started
