---
- name: Verify that MaxMind information is provided
  ansible.builtin.fail:
    msg: This role requires a MaxMind account ID and license key.
  when:
    - geoip2_maxmind_account_id is not defined or geoip2_maxmind_license_key is not defined

# Install some necessary prerequisites
- name: Install prerequisites
  ansible.builtin.package:
    name:
      - gzip
      - tar

- name: Ensure the directory in which to store the database file exists
  ansible.builtin.file:
    mode: 0755
    path: "{{ geoip2_database_directory }}"
    state: directory

- name: Install the specified MaxMind database edition
  ansible.builtin.include_tasks: install_database_edition.yml
  loop: "{{ geoip2_maxmind_editions }}"
  loop_control:
    loop_var: database_edition
