---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-geoip2
      ansible.builtin.include_role:
        name: ansible-role-geoip2
      vars:
        geoip2_maxmind_license_key: "{{ lookup('aws_ssm', '/cyhy/core/geoip/license_key', region='us-east-1') }}"
